export const ALL_TEXT_REQUEST = "ALL_TEXT_REQUEST";
export const ALL_TEXT_SUCCESS = "ALL_TEXT_SUCCESS";
export const ALL_TEXT_FAIL = "ALL_TEXT_FAIL";
export const NEW_TEXT_REQUEST = "NEW_TEXT_REQUEST";
export const NEW_TEXT_SUCCESS = "NEW_TEXT_SUCCESS";
export const NEW_TEXT_RESET = "NEW_TEXT_RESET";
export const NEW_TEXT_FAIL = "NEW_TEXT_FAIL";

export const NEW_MEETING_REQUEST = "NEW_MEETING_REQUEST";
export const NEW_MEETING_SUCCESS = "NEW_MEETING_SUCCESS";
export const NEW_MEETING_FAIL = "NEW_MEETING_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
